[cache]
dir = "~/.cache/pypoetry"

[experimental]
system-git-client = false

[installer]
max-workers = null
modern-installation = true
no-binary = null
parallel = true

[keyring]
enabled = true

[solver]
lazy-wheel = true

[virtualenvs]
create = true
in-project = true
prefer-active-python = true
prompt = "{project_name}-py{python_version}"

[virtualenvs.options]
always-copy = false
no-pip = false
no-setuptools = false
system-site-packages = false

[warnings]
export = true

